#!/bin/bash -e

source lib/functions.sh

CWD=$(pwd)
umask 022

STRAP_STAGE2_DIR=$CWD/rootfs

msg "Testing proot execution..."

proot_run_cmd_tools $1 'ls -la; echo $PATH'

msg "Injecting dummy.c..."

echo 'int main(){}' > $STRAP_STAGE2_DIR/dummy.c

msg "Compiling dummy.c..."

proot_run_cmd_tools $1 "gcc dummy.c -v -Wl,--verbose &> dummy.log"

msg "Output log..."

cat $STRAP_STAGE2_DIR/dummy.log

msg "Checking failed..."

cat $STRAP_STAGE2_DIR/dummy.log | grep failed

msg "Looking at sanity check..."

readelf -l $STRAP_STAGE2_DIR/a.out

msg "Done with tests..."
